[general]
import = ["/home/kerwood/.config/alacritty/dracula.toml"]

[font]
size = 9.0
# normal = { family = "Hack Nerd Font Mono", style = "Regular" }
normal = { family = "FiraCode Nerd Font Mono", style = "Regular" }

[selection]
save_to_clipboard = true

[window]
title = "Powered by a bunch of small penguins.."

[window.dimensions]
columns = 250
lines = 60

[window.padding]
x = 10
y = 10
